#!/bin/bash

API_NAME="Quarkey"
API_VERSION="v1"
API_HOST="127.0.0.1"
API_PORT="8000"

API_EMAIL_EXPEDITOR="quarkey.check.dev@gmail.com"
API_EMAIL_EXPEDITOR_PASS="sehp3C2GZTYf252u"

API_LOG="True"
API_LOG_DIR="./logs"

API_DB_TYPE="MYSQL"
API_DB_NAME="quarkey_dev"
API_DB_FILE="app.db"
API_DB_HOST="127.0.0.1"
API_DB_PORT="5432"
API_DB_USER="quarkey_dev"
API_DB_PASS="mdr"

export API_NAME API_VERSION API_HOST API_PORT API_EMAIL_EXPEDITOR API_EMAIL_EXPEDITOR_PASS API_LOG API_LOG_DIR API_DB_TYPE API_DB_NAME API_DB_FILE API_DB_HOST API_DB_PORT API_DB_USER API_DB_PASS

cd .. && python3 ./launch.py

